name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        # Not necessary because wrong version numbers do no harm in testing, but
        # may be useful in the future.
        fetch-depth: 0
        fetch-tags: true
        submodules: true
        persist-credentials: false

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true

    - name: Enable UBSan
      run: echo "CXXFLAGS=$UBSAN_FLAGS $CXXFLAGS" >> "$GITHUB_ENV"
      if: runner.os != 'Windows'
      env:
        UBSAN_FLAGS: -fsanitize=undefined -fsanitize-undefined-trap-on-error

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: pytest
      timeout-minutes: 30
