name: Release

on:
  push:
    tags: ["v*"]

jobs:
  sdist:
    name: Release source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true
        persist-credentials: false

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-sdist
        path: dist/*.tar.gz

  wheels:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    name: Release wheels on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true
        persist-credentials: false

    - uses: pypa/cibuildwheel@v2.17.0
      env:
        CIBW_ARCHS: auto64
        CIBW_ARCHS_MACOS: "auto64 universal2"
        # We do not support PyPy (for now).
        CIBW_SKIP: "pp*"

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-wheel-${{ matrix.platform }}
        path: wheelhouse/*.whl

  upload:
    needs: [sdist, wheels]
    name: Upload artifacts to assets
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: actions/download-artifact@v4
      with:
        pattern: artifact-*
        path: dist
        merge-multiple: true

    - name: Create checksums
      run: sha256sum * > SHA256SUMS
      working-directory: dist

    - name: Extract release note
      run: |
        awk -v v='${{ github.ref_name }}' \
          '/^## v[0-9]/{if($2==v){p=1;next}else{p=0}};p' \
          CHANGELOG.md > relnote

    - uses: softprops/action-gh-release@v1
      with:
        body_path: relnote
        files: dist/*
